//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace CRUD_using_Repository.Models
{
    

    public partial class Employee
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please Enter First Name")]
        [Display(Name ="Fisrst Name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage ="Please Enter Last Name")]
        [Display(Name ="Last Name")]
        public string LastName { get; set; }
        [Required(ErrorMessage ="Please Enter Age")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage ="Please Enter Position")]
        public string Position { get; set; }
        [Required(ErrorMessage ="Please Enter Office")]
        public string Office { get; set; }
        [Required(ErrorMessage ="Please Enter Salary")]
        public Nullable<int> Salary { get; set; }
    }
}
